############################
## Navbar
############################

main:
- name: "Home"
  url: "/""
  weight: 10
- name: "Research"
  url: "/research/"
  weight: 20
- name: "About"
  url: "/about/"
  weight: 30
