name: Auto-Merge
on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: read
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.user.login == 'renovate[bot]'
    steps:
    - uses: pascalgn/automerge-action@v0.16.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_LABELS: auto-merge
        MERGE_COMMIT_MESSAGE: "{pullRequest.title} ({pullRequest.number})"